spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  web:
    resources:
      static-locations: file:uploads/
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      file: compose.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/2025/02/23-01-changelog.yaml

server:
  port: 8445
