name: co_trade

services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=co_trade'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5434:5432'

